services:
  # Backend service
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: memos-backend
    ports:
      - "3001:8080"
    env_file:
      - ./apps/backend/.env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - memos-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/health || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Frontend service
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: memos-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - memos-network

  # MCP service
  mcp:
    build:
      context: ./apps/mcp
      dockerfile: Dockerfile.dev
    container_name: memos-mcp
    ports:
      - "3002:8080"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT= # Clear any PORT variable to use environment logic
      - BACKEND_API_URL=http://backend:8080
    volumes:
      - ./apps/mcp:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - memos-network

networks:
  memos-network:
    driver: bridge
