version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: memos-postgres
    environment:
      POSTGRES_DB: memos
      POSTGRES_USER: memos_user
      POSTGRES_PASSWORD: memos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/database.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memos_user -d memos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
